use_frameworks!

target 'PinterestSwift_Example' do
  pod 'PinterestSwift', :path => '../'

  target 'PinterestSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
